title: Ormesome on GitHub
email: david.orme@outlook.com
# logo: logo-white.png
baseurl: ""
url: "https://ormesome.github.io"
#twitter_username: "ormesome"
#github_username:  "ormesome"

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
show_downloads: false
# google_analytics:

collections:
  projects:
    output: true
    permalink: /:collection/:name
