title: Ormesome on GitHub
description: A site to say how awesome I am.
email: david.orme@outlook.com
# logo: logo-white.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ormesome.github.io"
#twitter_username: "ormesome"
#github_username:  "ormesome"

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
show_downloads: false
# google_analytics:

collections:
  projects:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: date

include: ['_pages']
