@startuml
  title Simple Architecture Diagram for OAuth

  actor user
  artifact webpage
  component webserver
  component authserver
  cloud google
  cloud facebook
  cloud github
  database webdatabase
  database authdatabase

  user -- webpage
  webpage -- webserver
  webserver -- authserver
  webserver -- webdatabase
  authserver -- authdatabase
  webserver -- google
  webserver -- facebook
  webserver -- github

@enduml